apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: platform
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: http://host.k3d.internal:8081/root/cert-manager-helm.git
    targetRevision: main
    path: chart
    helm:
      releaseName: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
